import fs from 'fs';

let content = fs.readFileSync('.env', 'utf-8');
const correctToken = "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI3YmMzODUwYTY5NzE0NzE3M2RlY2FlY2IwYjY2NDExMiIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiN2JjMzg1MGE2OTcxNDcxNzNkZWNhZWNiMGI2NjQxMTIiLCJpYXQiOjE3NzIwNTA2MzN9.ChC2oNtGns0pV5A_p_rz9SraV0BDMxsKeBAx7weV8cGtSQgcGfVEN3xCFsqnFaXiyZK5qnLhceEBAVCnDtijBwzsos6M_AomBVtrH2d2G8yAcul0czzf1QBRvfPz8qY12UhdTJ25paFe2OuUdDlyHQ5WtvgagKfqmE_T0ad_evxtffib3qZ-JGxQD5dBw1mwIg8stUZ5E5MwOap0AS1xBkAmJVTNZWv3ieMqgYrY88X2gXyE_lUb9dnKROipj5eIg7F4P-uk2UyrCIE6Y5p7RkG8TNiIkRlpRUvQOmiZZlEmASVfm0ee4V1cYbM1JrG80RvxhTjnrlJSOaLWxaJuWEpKdxjFMdx3egjYaY3a658JvhacBBW6WOprLU8d58d-kZpkjPJKRpV3tJN1UhS-1DZ9q5rvfr8B_ybaNPhdr7mHN4TODbRUd0y9R3Xn8_VdEU2bujzdQDJX3Rf62I6-01Ucp9VCN_pohO-wVLoPK0q_OfHkwzXBpnJN4WI24JELtLABt5ByoOnon1w8f3bibCDqi_U6IoTzJdHbzpJvBdIA3wuWbtjaoVFhXbIImUhf-8B-wO7zFF7J_uH9d-ovWe9apw-b11-TEqWVnZCGrtq8pQl9EyPW1xbG4OGEUoQfoxFHadKiuO-v8ZpLKEDrKLFLyyMPHaaZkVPxGl2fGmA";

const newLines = [];
const lines = content.split('\n');
for (let line of lines) {
    if (line.trim().startsWith('METAAPI_TOKEN=')) {
        newLines.push(`METAAPI_TOKEN=${correctToken}`);
    } else {
        newLines.push(line);
    }
}

fs.writeFileSync('.env', newLines.join('\n'));
console.log("Replaced ENV correctly.");
